[package]
name = "rc5"
version = "0.1.0"
authors = ["Oleks Pickle <22867443+olekspickle@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = {version = "4.0.29", features = ["derive"]}

