# See documentation for this config file at https://github.com/crate-ci/typos/blob/master/docs/reference.md
[files]
extend-exclude = [
    # Exclude generated files that are checked in to source control
    "package-lock.json",
    "Cargo.lock",
    ".github/workflows",
]
